name: HoloSports-Hub
version: ${project.version}_RELEASE-${git.commit.id.abbrev}
main: com.covercorp.holosports.hub.HoloSportsHub
author: COVER Corp.
api-version: 1.13
depend: [HoloSports-Commons, PlayerNPC]